# Generated by Django 5.0.2 on 2024-02-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_input',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_input', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
