# Generated by Django 5.0.2 on 2024-02-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_user_input'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_input',
            old_name='user_input',
            new_name='user_input_text',
        ),
    ]
